image: WMF 5

version: 0.3.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /update(?:|d|s) readme\..*/
skip_tags: true

environment:
  PSGalleryApiKey:
    secure: Xpt1sogACnm41S2/1LmhjIl1zn/s1u1dcwNdhLcUh8RA8eOSGaMGB8Ce8B5svBzg
  CODECOV_TOKEN:
    secure: t4VvkPdT9RkUoInm0NX1IloN5e7iqUNLMuQy9XhQIVZyo/KT+hZcIKox5bAbjWyr



install:
# Bootstrap PSDepend and Install Dependencies
- ps: |
    Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force
    Install-Module -Name PSDepend -Force; Import-Module -Name PSDepend
    Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force



build_script:
- ps: Invoke-psake '.\.scripts\build.ps1' -Properties @{'SkipBootStrap' = $true}



deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  description: |
    MsiHandler v$(appveyor_build_version) install is simple via PowerShell:
    
    ```powershell
    Install-Module MsiHandler -MinimumVersion $(appveyor_build_version)
    ```
    
    [The raw nupkg file is available via PowerShell Gallery](https://www.powershellgallery.com/packages/MsiHandler/$(appveyor_build_version)#manual-download).
  provider: GitHub
  auth_token:
    secure: QHZ4MqboF4PW2/fTZ36UmXmru7Va8Hds5kGN6KB1HL4NcnGlAXKemtHZVnbJ804F
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only



on_success:
# If build was started by pushed tag; deploy it.
- ps: |
    if (($env:APPVEYOR_REPO_BRANCH -eq 'master')) {
      Write-Host "[AppVeyor] On Success; deploying ..." -Foregroundcolor Green
      Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force
    }